### ISSUE TITLE
Upgrade alb to the newest version of consul-template

### ISSUE THREAD

**Issue by oscarrenalias** [Accenture/tldr#15]
According to https://github.com/hashicorp/consul-template/issues/442, there's a new build of consul-template that uses the latest Golang release that fixes the issue with multiple haproxy processes running together. This should allow us to move to the newest version of consul-template, instead of the one we're using now.

**Comment by SirIle** [comment]
Created a PR.

**Comment by oscarrenalias** [comment]
Merged, thanks!
