### ISSUE TITLE
Provisioning of registry node to AWS fails on Windows

### ISSUE THREAD

**Issue by ronistrom** [Accenture/tldr#6]
Hi,

Registry server volume mounting seems to fail on Windows machine when start-script is executed in Git Bash.

$ ./start.sh
**\* Setting up registry server ***
Using provider: aws
Creating private registry server on AWS
Running pre-create checks...
Creating machine...
(tldr-registry-aws) Launching instance...

-------- SNIP: Skipping lines -------- 

Starting Registrator
docker: Error response from daemon: Invalid bind mount spec "C:\Program Files\Git\var\run\docker.sock;C:\Users\RONI~1.STR\AppData\Local\Temp\docker.sock": volumeinvalidmode: invalid mode: "\Users\RONI~1.STR\AppData\Local\Temp\docker.sock".
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

-------- SNIP: Skipping lines -------- 

Error: No such image or container: registrator
ERROR: Registrator was not successfully started.

**Comment by oscarrenalias** [comment]
Can you see if the fixes in branch "bugfix/6" work for you?

**Comment by ronistrom** [comment]
Worked. However the cAdvisor has the same issue. Created a pull request for similar kind of fixes for cAdvisor.
